import { Button } from "../widgets/button.slint";
import { Theme } from "../theme.slint";
export component Home inherits Rectangle {
    VerticalLayout {
        alignment: center;
        spacing: 4px;
        HorizontalLayout {
            alignment: center;
            spacing: 4px;

            Button {
                text: "Add path";
                variant: Theme.primary;
                clicked => {
                    debug("clicked");
                }
            }

            Button {
                text: "Add path";
                variant: Theme.success;
                clicked => {
                    debug("clicked");
                }
            }

            Button {
                text: "Add path";
                variant: Theme.info;
                clicked => {
                    debug("clicked");
                }
            }

            Button {
                text: "Add path";
                variant: Theme.danger;
                clicked => {
                    debug("clicked");
                }
            }

            Button {
                text: "Add path";
                variant: Theme.warning;
                clicked => {
                    debug("clicked");
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            spacing: 4px;

            Button {
                text: "Add path";
                variant: Theme.primary;
                outline: true;
                clicked => {
                    debug("clicked");
                }
            }

            Button {
                text: "Add path";
                variant: Theme.success;
                outline: true;
                clicked => {
                    debug("clicked");
                }
            }

            Button {
                text: "Add path";
                variant: Theme.info;
                outline: true;
                clicked => {
                    debug("clicked");
                }
            }

            Button {
                text: "Add path";
                variant: Theme.danger;
                outline: true;
                clicked => {
                    debug("clicked");
                }
            }

            Button {
                text: "Add path";
                variant: Theme.warning;
                outline: true;
                clicked => {
                    debug("clicked");
                }
            }
        }
    }
}
