name = "slint-template"
product-name = "slint-template"
version = "0.1.0"
identifier = "com.app.slint-template"
description = "A slint project template for Rust with bundling github actions."
category = "Utility"
homepage = "https://github.com/uAtomicBoolean/slint-template"
license-file = "LICENSE"
publisher = "uAtomicBoolean"
authors = ["uAtomicBoolean"]
Legal-copyright = "Copyright uAtomicBoolean © 2026"


formats = ["nsis", "wix"]
out-dir = "dist/"
binaries-dir = "target/release"
resources = ["Cargo.toml", "src", "res/icon.ico"]
icons = ["res/icon.ico"]
before-packaging-command = "cargo build --release"

[nsis]
installer-mode = "perMachine"
installer-icon = "res/icon.ico"
