import { VariableColor } from "theme-structs.slint";

export global Colors {
    out property <VariableColor> neutral: {
        e-50: #fafafa,
        e-100: #f5f5f5,
        e-200: #e5e5e5,
        e-300: #d4d4d4,
        e-400: #a3a3a3,
        e-500: #737373,
        e-600: #525252,
        e-700: #404040,
        e-800: #262626,
        e-900: #171717,
        e-950: #0a0a0a,
    };
    out property <VariableColor> blue: {
        e-50: #eff6ff,
        e-100: #dbeafe,
        e-200: #bfdbfe,
        e-300: #93c5fd,
        e-400: #60a5fa,
        e-500: #3b82f6,
        e-600: #2563eb,
        e-700: #1d4ed8,
        e-800: #1e40af,
        e-900: #1e3a8a,
        e-950: #172554,
    };
    out property <VariableColor> red: {
        e-50: #fef2f2,
        e-100: #fee2e2,
        e-200: #fecaca,
        e-300: #fca5a5,
        e-400: #f87171,
        e-500: #ef4444,
        e-600: #dc2626,
        e-700: #b91c1c,
        e-800: #991b1b,
        e-900: #7f1d1d,
        e-950: #450a0a,
    };
    out property <VariableColor> green: {
        e-50: #f0fdf4,
        e-100: #dcfce7,
        e-200: #bbf7d0,
        e-300: #86efac,
        e-400: #4ade80,
        e-500: #22c55e,
        e-600: #16a34a,
        e-700: #15803d,
        e-800: #166534,
        e-900: #14532d,
        e-950: #052e16,
    };
    out property <VariableColor> yellow: {
        e-50: #fefce8,
        e-100: #fef9c3,
        e-200: #fef08a,
        e-300: #fde047,
        e-400: #facc15,
        e-500: #eab308,
        e-600: #ca8a04,
        e-700: #a16207,
        e-800: #854d0e,
        e-900: #713f12,
        e-950: #422006,
    };
}

export global Sizes {
    out property <length> border-radius-small: 2px;
    out property <length> border-radius-base: 4px;
    out property <length> border-radius-large: 8px;
    out property <length> border-radius-round: 20px;
    out property <length> border-radius-circle: 9999px;
}
