export global ColorSettings {
    out property <color> grey-50: #fafafa;
    out property <color> grey-100: #f4f4f5;
    out property <color> grey-200: #e4e4e7;
    out property <color> grey-300: #d4d4d8;
    out property <color> grey-400: #a1a1aa;
    out property <color> grey-500: #71717a;
    out property <color> grey-600: #52525b;
    out property <color> grey-700: #3f3f46;
    out property <color> grey-800: #27272a;
    out property <color> grey-900: #18181b;
    out property <color> grey-950: #09090b;
    out property <color> primary-50: #fef2f2;
    out property <color> primary-100: #fee2e2;
    out property <color> primary-200: #fecaca;
    out property <color> primary-300: #fca5a5;
    out property <color> primary-400: #f87171;
    out property <color> primary-500: #ef4444;
    out property <color> primary-600: #dc2626;
    out property <color> primary-700: #b91c1c;
    out property <color> primary-800: #991b1b;
    out property <color> primary-900: #7f1d1d;
    out property <color> primary-950: #450a0a;
}
