export global Theme {
    out property <color> primary: #409eff;
    out property <color> success: #67c23a;
    out property <color> warning: #e6a23c;
    out property <color> danger: #f56c6c;
    out property <color> info: #909399;

    out property <color> white-10: #53a8ff;
    out property <color> white-20: #66b1ff;
    out property <color> white-30: #79bbff;
    out property <color> white-40: #8cc5ff;
    out property <color> white-50: #a0cfff;
    out property <color> white-60: #b3d8ff;
    out property <color> white-70: #c6e2ff;
    out property <color> white-80: #d9ecff;
    out property <color> white-90: #ecf5ff;

    out property <color> border: #e5e7eb;
    out property <length> border-radius-small: 2px;
    out property <length> border-radius-base: 4px;
    out property <length> border-radius-large: 8px;
    out property <length> border-radius-round: 20px;
    out property <length> border-radius-circle: 9999px;

    out property <color> text-primary: #303133;
    out property <color> text-regular: #606266;
    out property <color> text-secondary: #909399;
    out property <color> text-placeholder: #a8abb2;
    out property <color> text-disabled: #c0c4cc;
}
