name: "Build"
run-name: "Build the executable and its installers and create a release."

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4


      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
      
      - name: Package the project
        run: |
          cargo install cargo-packager --locked
          cargo packager --release

      - name: Rename binary
        run: |
          if [ "${{ matrix.platform }}" == "ubuntu-22.04" ]; then
            mv target/release/slint-template target/release/slint-template_${{ github.ref.name }}_linux_standalone
          elif [ "${{ matrix.platform }}" == "windows-latest" ]; then
            mv target/release/slint-template.exe target/release/slint-template_${{ github.ref.name }}_windows_standalone.exe
          elif [ "${{ matrix.platform }}" == "macos-latest" ]; then
            mv target/release/slint-template target/release/slint-template_${{ github.ref.name }}_macos_standalone
          fi
        shell: bash
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: slint-template ${{ github.ref_name }}
          files: |
            target/release/slint-template_${{ github.ref.name }}_linux_standalone
            target/release/slint-template_${{ github.ref.name }}_windows_standalone.exe
            target/release/slint-template_${{ github.ref.name }}_macos_standalone
            dist/slint-template*
