name: Windows
run-name: Build project

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Package the project
        run: |
          cargo install cargo-packager --locked
          cargo packager --release

      - name: Rename binary
        run: |
          cp target/release/scriptboard target/release/scriptboard-${{ github.ref_name }}-x86_64-windows
        shell: bash
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: scriptboard v${{ github.ref_name }}
          files: |
            target/release/scriptboard-${{ github.ref_name }}-x86_64-windows
            dist/scriptboard*
